<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>

        <OutputType>Exe</OutputType>

        <RootNamespace>rgn</RootNamespace>
        <AssemblyName>rgn</AssemblyName>
        <TargetFramework>net8.0</TargetFramework>
        <FileAlignment>512</FileAlignment>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <LangVersion>9</LangVersion>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>bin\Debug\</OutputPath>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\Release\</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <ItemGroup>
       
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="BulletSharp" Version="0.11.1" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>
    <ItemGroup>
      <Compile Remove="Achievement.cs" />
      <Compile Remove="Camera.cs" />
      <Compile Remove="Car.cs" />
      <Compile Remove="Clutch.cs" />
      <Compile Remove="Differential.cs" />
      <Compile Remove="Driver.cs" />
      <Compile Remove="File.cs" />
      <Compile Remove="Gearbox.cs" />
      <Compile Remove="MBA.cs" />
      <Compile Remove="Rigid.cs" />
      <Compile Remove="Suspension.cs" />
      <Compile Remove="Timer.cs" />
      <Compile Remove="Weather.cs" />
    </ItemGroup>

    <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
         Other similar extension points exist, see Microsoft.Common.targets.
    <Target Name="BeforeBuild">
    </Target>
    <Target Name="AfterBuild">
    </Target>
    -->

</Project>
